inherit_gem:
  # https://github.com/Shopify/ruby-style-guide/blob/main/rubocop.yml
  rubocop-shopify: rubocop.yml

# Rails:
#   Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - include
    - render
    - redirect_to

Layout/LineLength:
  Max: 160
